// Code generated by ent, DO NOT EDIT.

package perms

import (
	"time"
)

const (
	// Label holds the string label denoting the perms type in the database.
	Label = "perms"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGuyukCd holds the string denoting the guyuk_cd field in the database.
	FieldGuyukCd = "guyuk_cd"
	// FieldGuyukCdNm holds the string denoting the guyuk_cd_nm field in the database.
	FieldGuyukCdNm = "guyuk_cd_nm"
	// FieldJimokCd holds the string denoting the jimok_cd field in the database.
	FieldJimokCd = "jimok_cd"
	// FieldJimokCdNm holds the string denoting the jimok_cd_nm field in the database.
	FieldJimokCdNm = "jimok_cd_nm"
	// FieldJiyukCd holds the string denoting the jiyuk_cd field in the database.
	FieldJiyukCd = "jiyuk_cd"
	// FieldJiyukCdNm holds the string denoting the jiyuk_cd_nm field in the database.
	FieldJiyukCdNm = "jiyuk_cd_nm"
	// FieldJiguCd holds the string denoting the jigu_cd field in the database.
	FieldJiguCd = "jigu_cd"
	// FieldJiguCdNm holds the string denoting the jigu_cd_nm field in the database.
	FieldJiguCdNm = "jigu_cd_nm"
	// FieldArchGBCdNm holds the string denoting the arch_gb_cd_nm field in the database.
	FieldArchGBCdNm = "arch_gb_cd_nm"
	// FieldArchGBCd holds the string denoting the arch_gb_cd field in the database.
	FieldArchGBCd = "arch_gb_cd"
	// FieldPlatArea holds the string denoting the plat_area field in the database.
	FieldPlatArea = "plat_area"
	// FieldArchArea holds the string denoting the arch_area field in the database.
	FieldArchArea = "arch_area"
	// FieldBcRat holds the string denoting the bc_rat field in the database.
	FieldBcRat = "bc_rat"
	// FieldTotArea holds the string denoting the tot_area field in the database.
	FieldTotArea = "tot_area"
	// FieldVlRatEstmTotArea holds the string denoting the vl_rat_estm_tot_area field in the database.
	FieldVlRatEstmTotArea = "vl_rat_estm_tot_area"
	// FieldVlRat holds the string denoting the vl_rat field in the database.
	FieldVlRat = "vl_rat"
	// FieldMainBldCnt holds the string denoting the main_bld_cnt field in the database.
	FieldMainBldCnt = "main_bld_cnt"
	// FieldAtchBldDongCnt holds the string denoting the atch_bld_dong_cnt field in the database.
	FieldAtchBldDongCnt = "atch_bld_dong_cnt"
	// FieldMainPurpsCd holds the string denoting the main_purps_cd field in the database.
	FieldMainPurpsCd = "main_purps_cd"
	// FieldMainPurpsCdNm holds the string denoting the main_purps_cd_nm field in the database.
	FieldMainPurpsCdNm = "main_purps_cd_nm"
	// FieldHhldCnt holds the string denoting the hhld_cnt field in the database.
	FieldHhldCnt = "hhld_cnt"
	// FieldHoCnt holds the string denoting the ho_cnt field in the database.
	FieldHoCnt = "ho_cnt"
	// FieldFmlyCnt holds the string denoting the fmly_cnt field in the database.
	FieldFmlyCnt = "fmly_cnt"
	// FieldTotPkngCnt holds the string denoting the tot_pkng_cnt field in the database.
	FieldTotPkngCnt = "tot_pkng_cnt"
	// FieldStcnsSchedDay holds the string denoting the stcns_sched_day field in the database.
	FieldStcnsSchedDay = "stcns_sched_day"
	// FieldStcnsDelayDay holds the string denoting the stcns_delay_day field in the database.
	FieldStcnsDelayDay = "stcns_delay_day"
	// FieldRealStcnsDay holds the string denoting the real_stcns_day field in the database.
	FieldRealStcnsDay = "real_stcns_day"
	// FieldArchPmsDay holds the string denoting the arch_pms_day field in the database.
	FieldArchPmsDay = "arch_pms_day"
	// FieldUseAprDay holds the string denoting the use_apr_day field in the database.
	FieldUseAprDay = "use_apr_day"
	// FieldPlatPlc holds the string denoting the plat_plc field in the database.
	FieldPlatPlc = "plat_plc"
	// FieldSigunguCd holds the string denoting the sigungu_cd field in the database.
	FieldSigunguCd = "sigungu_cd"
	// FieldBjdongCd holds the string denoting the bjdong_cd field in the database.
	FieldBjdongCd = "bjdong_cd"
	// FieldPlatGBCd holds the string denoting the plat_gb_cd field in the database.
	FieldPlatGBCd = "plat_gb_cd"
	// FieldBun holds the string denoting the bun field in the database.
	FieldBun = "bun"
	// FieldJi holds the string denoting the ji field in the database.
	FieldJi = "ji"
	// FieldMgmPmsrgstPk holds the string denoting the mgm_pmsrgst_pk field in the database.
	FieldMgmPmsrgstPk = "mgm_pmsrgst_pk"
	// FieldSplotNm holds the string denoting the splot_nm field in the database.
	FieldSplotNm = "splot_nm"
	// FieldBlock holds the string denoting the block field in the database.
	FieldBlock = "block"
	// FieldLot holds the string denoting the lot field in the database.
	FieldLot = "lot"
	// FieldCrtnDay holds the string denoting the crtn_day field in the database.
	FieldCrtnDay = "crtn_day"
	// FieldRnum holds the string denoting the rnum field in the database.
	FieldRnum = "rnum"
	// FieldBldNm holds the string denoting the bld_nm field in the database.
	FieldBldNm = "bld_nm"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the perms in the database.
	Table = "perms"
)

// Columns holds all SQL columns for perms fields.
var Columns = []string{
	FieldID,
	FieldGuyukCd,
	FieldGuyukCdNm,
	FieldJimokCd,
	FieldJimokCdNm,
	FieldJiyukCd,
	FieldJiyukCdNm,
	FieldJiguCd,
	FieldJiguCdNm,
	FieldArchGBCdNm,
	FieldArchGBCd,
	FieldPlatArea,
	FieldArchArea,
	FieldBcRat,
	FieldTotArea,
	FieldVlRatEstmTotArea,
	FieldVlRat,
	FieldMainBldCnt,
	FieldAtchBldDongCnt,
	FieldMainPurpsCd,
	FieldMainPurpsCdNm,
	FieldHhldCnt,
	FieldHoCnt,
	FieldFmlyCnt,
	FieldTotPkngCnt,
	FieldStcnsSchedDay,
	FieldStcnsDelayDay,
	FieldRealStcnsDay,
	FieldArchPmsDay,
	FieldUseAprDay,
	FieldPlatPlc,
	FieldSigunguCd,
	FieldBjdongCd,
	FieldPlatGBCd,
	FieldBun,
	FieldJi,
	FieldMgmPmsrgstPk,
	FieldSplotNm,
	FieldBlock,
	FieldLot,
	FieldCrtnDay,
	FieldRnum,
	FieldBldNm,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
