// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BjdsColumns holds the columns for the "bjds" table.
	BjdsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "bjdong_cd", Type: field.TypeString},
		{Name: "sigungu_cd", Type: field.TypeString},
		{Name: "sido_nm", Type: field.TypeString},
		{Name: "sigungu_nm", Type: field.TypeString},
		{Name: "dong_nm", Type: field.TypeString},
		{Name: "li_nm", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// BjdsTable holds the schema information for the "bjds" table.
	BjdsTable = &schema.Table{
		Name:       "bjds",
		Columns:    BjdsColumns,
		PrimaryKey: []*schema.Column{BjdsColumns[0]},
	}
	// DemolsColumns holds the columns for the "demols" table.
	DemolsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "mgm_pmsrgst_pk", Type: field.TypeString},
		{Name: "bld_nm", Type: field.TypeString, Nullable: true},
		{Name: "demol_extng_gb_cd", Type: field.TypeString, Nullable: true},
		{Name: "demol_extng_gb_cd_nm", Type: field.TypeString, Nullable: true},
		{Name: "demol_strt_day", Type: field.TypeString, Nullable: true},
		{Name: "demol_end_day", Type: field.TypeString, Nullable: true},
		{Name: "demol_extng_day", Type: field.TypeString, Nullable: true},
		{Name: "tot_area", Type: field.TypeUint32, Nullable: true},
		{Name: "bld_cnt", Type: field.TypeUint32, Nullable: true},
		{Name: "main_purps_cd", Type: field.TypeString, Nullable: true},
		{Name: "main_purps_cd_nm", Type: field.TypeString, Nullable: true},
		{Name: "strct_cd", Type: field.TypeString, Nullable: true},
		{Name: "strct_cd_nm", Type: field.TypeString, Nullable: true},
		{Name: "hhld_cnt", Type: field.TypeString, Nullable: true},
		{Name: "ho_cnt", Type: field.TypeString, Nullable: true},
		{Name: "crtn_day", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "jibun_demol", Type: field.TypeInt, Nullable: true},
	}
	// DemolsTable holds the schema information for the "demols" table.
	DemolsTable = &schema.Table{
		Name:       "demols",
		Columns:    DemolsColumns,
		PrimaryKey: []*schema.Column{DemolsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "demols_jibuns_demol",
				Columns:    []*schema.Column{DemolsColumns[19]},
				RefColumns: []*schema.Column{JibunsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// JibunsColumns holds the columns for the "jibuns" table.
	JibunsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "bjdong_cd", Type: field.TypeString},
		{Name: "sigungu_cd", Type: field.TypeString},
		{Name: "bun", Type: field.TypeString},
		{Name: "ji", Type: field.TypeString},
		{Name: "guyuk_cd", Type: field.TypeString},
		{Name: "guyuk_cd_nm", Type: field.TypeString},
		{Name: "jimok_cd", Type: field.TypeString},
		{Name: "jimok_cd_nm", Type: field.TypeString},
		{Name: "jiyuk_cd", Type: field.TypeString},
		{Name: "jiyuk_cd_nm", Type: field.TypeString},
		{Name: "jigu_cd", Type: field.TypeString},
		{Name: "jigu_cd_nm", Type: field.TypeString},
		{Name: "plat_gb_cd", Type: field.TypeString},
		{Name: "plat_plc", Type: field.TypeString},
		{Name: "splot_nm", Type: field.TypeString},
		{Name: "block", Type: field.TypeString},
		{Name: "lot", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "bjd_jibun", Type: field.TypeInt, Nullable: true},
	}
	// JibunsTable holds the schema information for the "jibuns" table.
	JibunsTable = &schema.Table{
		Name:       "jibuns",
		Columns:    JibunsColumns,
		PrimaryKey: []*schema.Column{JibunsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "jibuns_bjds_jibun",
				Columns:    []*schema.Column{JibunsColumns[20]},
				RefColumns: []*schema.Column{BjdsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// PermsColumns holds the columns for the "perms" table.
	PermsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "guyuk_cd", Type: field.TypeString, Nullable: true},
		{Name: "guyuk_cd_nm", Type: field.TypeString, Nullable: true},
		{Name: "jimok_cd", Type: field.TypeString, Nullable: true},
		{Name: "jimok_cd_nm", Type: field.TypeString, Nullable: true},
		{Name: "jiyuk_cd", Type: field.TypeString, Nullable: true},
		{Name: "jiyuk_cd_nm", Type: field.TypeString, Nullable: true},
		{Name: "jigu_cd", Type: field.TypeString, Nullable: true},
		{Name: "jigu_cd_nm", Type: field.TypeString, Nullable: true},
		{Name: "arch_gb_cd_nm", Type: field.TypeString, Nullable: true},
		{Name: "arch_gb_cd", Type: field.TypeString, Nullable: true},
		{Name: "plat_area", Type: field.TypeUint32, Nullable: true},
		{Name: "arch_area", Type: field.TypeUint32, Nullable: true},
		{Name: "bc_rat", Type: field.TypeUint16, Nullable: true},
		{Name: "tot_area", Type: field.TypeUint32, Nullable: true},
		{Name: "vl_rat_estm_tot_area", Type: field.TypeUint32, Nullable: true},
		{Name: "vl_rat", Type: field.TypeUint16, Nullable: true},
		{Name: "main_bld_cnt", Type: field.TypeUint16, Nullable: true},
		{Name: "atch_bld_dong_cnt", Type: field.TypeUint16, Nullable: true},
		{Name: "main_purps_cd", Type: field.TypeString, Nullable: true},
		{Name: "main_purps_cd_nm", Type: field.TypeString, Nullable: true},
		{Name: "hhld_cnt", Type: field.TypeUint16, Nullable: true},
		{Name: "ho_cnt", Type: field.TypeUint16, Nullable: true},
		{Name: "fmly_cnt", Type: field.TypeUint16, Nullable: true},
		{Name: "tot_pkng_cnt", Type: field.TypeUint16, Nullable: true},
		{Name: "stcns_sched_day", Type: field.TypeString, Nullable: true},
		{Name: "stcns_delay_day", Type: field.TypeString, Nullable: true},
		{Name: "real_stcns_day", Type: field.TypeString, Nullable: true},
		{Name: "arch_pms_day", Type: field.TypeString, Nullable: true},
		{Name: "use_apr_day", Type: field.TypeString, Nullable: true},
		{Name: "plat_plc", Type: field.TypeString, Nullable: true},
		{Name: "sigungu_cd", Type: field.TypeString, Nullable: true},
		{Name: "bjdong_cd", Type: field.TypeString, Nullable: true},
		{Name: "plat_gb_cd", Type: field.TypeString, Nullable: true},
		{Name: "bun", Type: field.TypeString, Nullable: true},
		{Name: "ji", Type: field.TypeString, Nullable: true},
		{Name: "mgm_pmsrgst_pk", Type: field.TypeString, Unique: true},
		{Name: "splot_nm", Type: field.TypeString, Nullable: true},
		{Name: "block", Type: field.TypeString, Nullable: true},
		{Name: "lot", Type: field.TypeString, Nullable: true},
		{Name: "crtn_day", Type: field.TypeString, Nullable: true},
		{Name: "rnum", Type: field.TypeUint16, Nullable: true},
		{Name: "bld_nm", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PermsTable holds the schema information for the "perms" table.
	PermsTable = &schema.Table{
		Name:       "perms",
		Columns:    PermsColumns,
		PrimaryKey: []*schema.Column{PermsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BjdsTable,
		DemolsTable,
		JibunsTable,
		PermsTable,
	}
)

func init() {
	DemolsTable.ForeignKeys[0].RefTable = JibunsTable
	JibunsTable.ForeignKeys[0].RefTable = BjdsTable
}
