// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"gopms/ent/bjd"
	"gopms/ent/jibun"
	"gopms/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BjdQuery is the builder for querying Bjd entities.
type BjdQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.Bjd
	withJibun  *JibunQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BjdQuery builder.
func (bq *BjdQuery) Where(ps ...predicate.Bjd) *BjdQuery {
	bq.predicates = append(bq.predicates, ps...)
	return bq
}

// Limit the number of records to be returned by this query.
func (bq *BjdQuery) Limit(limit int) *BjdQuery {
	bq.ctx.Limit = &limit
	return bq
}

// Offset to start from.
func (bq *BjdQuery) Offset(offset int) *BjdQuery {
	bq.ctx.Offset = &offset
	return bq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bq *BjdQuery) Unique(unique bool) *BjdQuery {
	bq.ctx.Unique = &unique
	return bq
}

// Order specifies how the records should be ordered.
func (bq *BjdQuery) Order(o ...OrderFunc) *BjdQuery {
	bq.order = append(bq.order, o...)
	return bq
}

// QueryJibun chains the current query on the "jibun" edge.
func (bq *BjdQuery) QueryJibun() *JibunQuery {
	query := (&JibunClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(bjd.Table, bjd.FieldID, selector),
			sqlgraph.To(jibun.Table, jibun.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, bjd.JibunTable, bjd.JibunColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Bjd entity from the query.
// Returns a *NotFoundError when no Bjd was found.
func (bq *BjdQuery) First(ctx context.Context) (*Bjd, error) {
	nodes, err := bq.Limit(1).All(setContextOp(ctx, bq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{bjd.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bq *BjdQuery) FirstX(ctx context.Context) *Bjd {
	node, err := bq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Bjd ID from the query.
// Returns a *NotFoundError when no Bjd ID was found.
func (bq *BjdQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bq.Limit(1).IDs(setContextOp(ctx, bq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{bjd.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bq *BjdQuery) FirstIDX(ctx context.Context) int {
	id, err := bq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Bjd entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Bjd entity is found.
// Returns a *NotFoundError when no Bjd entities are found.
func (bq *BjdQuery) Only(ctx context.Context) (*Bjd, error) {
	nodes, err := bq.Limit(2).All(setContextOp(ctx, bq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{bjd.Label}
	default:
		return nil, &NotSingularError{bjd.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bq *BjdQuery) OnlyX(ctx context.Context) *Bjd {
	node, err := bq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Bjd ID in the query.
// Returns a *NotSingularError when more than one Bjd ID is found.
// Returns a *NotFoundError when no entities are found.
func (bq *BjdQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bq.Limit(2).IDs(setContextOp(ctx, bq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{bjd.Label}
	default:
		err = &NotSingularError{bjd.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bq *BjdQuery) OnlyIDX(ctx context.Context) int {
	id, err := bq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Bjds.
func (bq *BjdQuery) All(ctx context.Context) ([]*Bjd, error) {
	ctx = setContextOp(ctx, bq.ctx, "All")
	if err := bq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Bjd, *BjdQuery]()
	return withInterceptors[[]*Bjd](ctx, bq, qr, bq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bq *BjdQuery) AllX(ctx context.Context) []*Bjd {
	nodes, err := bq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Bjd IDs.
func (bq *BjdQuery) IDs(ctx context.Context) (ids []int, err error) {
	if bq.ctx.Unique == nil && bq.path != nil {
		bq.Unique(true)
	}
	ctx = setContextOp(ctx, bq.ctx, "IDs")
	if err = bq.Select(bjd.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bq *BjdQuery) IDsX(ctx context.Context) []int {
	ids, err := bq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bq *BjdQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bq.ctx, "Count")
	if err := bq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bq, querierCount[*BjdQuery](), bq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bq *BjdQuery) CountX(ctx context.Context) int {
	count, err := bq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bq *BjdQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bq.ctx, "Exist")
	switch _, err := bq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bq *BjdQuery) ExistX(ctx context.Context) bool {
	exist, err := bq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BjdQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bq *BjdQuery) Clone() *BjdQuery {
	if bq == nil {
		return nil
	}
	return &BjdQuery{
		config:     bq.config,
		ctx:        bq.ctx.Clone(),
		order:      append([]OrderFunc{}, bq.order...),
		inters:     append([]Interceptor{}, bq.inters...),
		predicates: append([]predicate.Bjd{}, bq.predicates...),
		withJibun:  bq.withJibun.Clone(),
		// clone intermediate query.
		sql:  bq.sql.Clone(),
		path: bq.path,
	}
}

// WithJibun tells the query-builder to eager-load the nodes that are connected to
// the "jibun" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BjdQuery) WithJibun(opts ...func(*JibunQuery)) *BjdQuery {
	query := (&JibunClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withJibun = query
	return bq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		BjdongCd string `json:"bjdong_cd,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Bjd.Query().
//		GroupBy(bjd.FieldBjdongCd).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bq *BjdQuery) GroupBy(field string, fields ...string) *BjdGroupBy {
	bq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BjdGroupBy{build: bq}
	grbuild.flds = &bq.ctx.Fields
	grbuild.label = bjd.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		BjdongCd string `json:"bjdong_cd,omitempty"`
//	}
//
//	client.Bjd.Query().
//		Select(bjd.FieldBjdongCd).
//		Scan(ctx, &v)
func (bq *BjdQuery) Select(fields ...string) *BjdSelect {
	bq.ctx.Fields = append(bq.ctx.Fields, fields...)
	sbuild := &BjdSelect{BjdQuery: bq}
	sbuild.label = bjd.Label
	sbuild.flds, sbuild.scan = &bq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BjdSelect configured with the given aggregations.
func (bq *BjdQuery) Aggregate(fns ...AggregateFunc) *BjdSelect {
	return bq.Select().Aggregate(fns...)
}

func (bq *BjdQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bq); err != nil {
				return err
			}
		}
	}
	for _, f := range bq.ctx.Fields {
		if !bjd.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bq.path != nil {
		prev, err := bq.path(ctx)
		if err != nil {
			return err
		}
		bq.sql = prev
	}
	return nil
}

func (bq *BjdQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Bjd, error) {
	var (
		nodes       = []*Bjd{}
		_spec       = bq.querySpec()
		loadedTypes = [1]bool{
			bq.withJibun != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Bjd).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Bjd{config: bq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bq.withJibun; query != nil {
		if err := bq.loadJibun(ctx, query, nodes,
			func(n *Bjd) { n.Edges.Jibun = []*Jibun{} },
			func(n *Bjd, e *Jibun) { n.Edges.Jibun = append(n.Edges.Jibun, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bq *BjdQuery) loadJibun(ctx context.Context, query *JibunQuery, nodes []*Bjd, init func(*Bjd), assign func(*Bjd, *Jibun)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Bjd)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Jibun(func(s *sql.Selector) {
		s.Where(sql.InValues(bjd.JibunColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.bjd_jibun
		if fk == nil {
			return fmt.Errorf(`foreign-key "bjd_jibun" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "bjd_jibun" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (bq *BjdQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bq.querySpec()
	_spec.Node.Columns = bq.ctx.Fields
	if len(bq.ctx.Fields) > 0 {
		_spec.Unique = bq.ctx.Unique != nil && *bq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bq.driver, _spec)
}

func (bq *BjdQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(bjd.Table, bjd.Columns, sqlgraph.NewFieldSpec(bjd.FieldID, field.TypeInt))
	_spec.From = bq.sql
	if unique := bq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bq.path != nil {
		_spec.Unique = true
	}
	if fields := bq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bjd.FieldID)
		for i := range fields {
			if fields[i] != bjd.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bq *BjdQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bq.driver.Dialect())
	t1 := builder.Table(bjd.Table)
	columns := bq.ctx.Fields
	if len(columns) == 0 {
		columns = bjd.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bq.sql != nil {
		selector = bq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bq.ctx.Unique != nil && *bq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bq.predicates {
		p(selector)
	}
	for _, p := range bq.order {
		p(selector)
	}
	if offset := bq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BjdGroupBy is the group-by builder for Bjd entities.
type BjdGroupBy struct {
	selector
	build *BjdQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bgb *BjdGroupBy) Aggregate(fns ...AggregateFunc) *BjdGroupBy {
	bgb.fns = append(bgb.fns, fns...)
	return bgb
}

// Scan applies the selector query and scans the result into the given value.
func (bgb *BjdGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bgb.build.ctx, "GroupBy")
	if err := bgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BjdQuery, *BjdGroupBy](ctx, bgb.build, bgb, bgb.build.inters, v)
}

func (bgb *BjdGroupBy) sqlScan(ctx context.Context, root *BjdQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bgb.fns))
	for _, fn := range bgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bgb.flds)+len(bgb.fns))
		for _, f := range *bgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BjdSelect is the builder for selecting fields of Bjd entities.
type BjdSelect struct {
	*BjdQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bs *BjdSelect) Aggregate(fns ...AggregateFunc) *BjdSelect {
	bs.fns = append(bs.fns, fns...)
	return bs
}

// Scan applies the selector query and scans the result into the given value.
func (bs *BjdSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bs.ctx, "Select")
	if err := bs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BjdQuery, *BjdSelect](ctx, bs.BjdQuery, bs, bs.inters, v)
}

func (bs *BjdSelect) sqlScan(ctx context.Context, root *BjdQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bs.fns))
	for _, fn := range bs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
