// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"gopms/ent/demol"
	"gopms/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DemolDelete is the builder for deleting a Demol entity.
type DemolDelete struct {
	config
	hooks    []Hook
	mutation *DemolMutation
}

// Where appends a list predicates to the DemolDelete builder.
func (dd *DemolDelete) Where(ps ...predicate.Demol) *DemolDelete {
	dd.mutation.Where(ps...)
	return dd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dd *DemolDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, DemolMutation](ctx, dd.sqlExec, dd.mutation, dd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dd *DemolDelete) ExecX(ctx context.Context) int {
	n, err := dd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dd *DemolDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(demol.Table, sqlgraph.NewFieldSpec(demol.FieldID, field.TypeInt))
	if ps := dd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dd.mutation.done = true
	return affected, err
}

// DemolDeleteOne is the builder for deleting a single Demol entity.
type DemolDeleteOne struct {
	dd *DemolDelete
}

// Where appends a list predicates to the DemolDelete builder.
func (ddo *DemolDeleteOne) Where(ps ...predicate.Demol) *DemolDeleteOne {
	ddo.dd.mutation.Where(ps...)
	return ddo
}

// Exec executes the deletion query.
func (ddo *DemolDeleteOne) Exec(ctx context.Context) error {
	n, err := ddo.dd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{demol.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ddo *DemolDeleteOne) ExecX(ctx context.Context) {
	if err := ddo.Exec(ctx); err != nil {
		panic(err)
	}
}
