// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"gopms/ent/demol"
	"gopms/ent/jibun"
	"gopms/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JibunQuery is the builder for querying Jibun entities.
type JibunQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.Jibun
	withDemol  *DemolQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the JibunQuery builder.
func (jq *JibunQuery) Where(ps ...predicate.Jibun) *JibunQuery {
	jq.predicates = append(jq.predicates, ps...)
	return jq
}

// Limit the number of records to be returned by this query.
func (jq *JibunQuery) Limit(limit int) *JibunQuery {
	jq.ctx.Limit = &limit
	return jq
}

// Offset to start from.
func (jq *JibunQuery) Offset(offset int) *JibunQuery {
	jq.ctx.Offset = &offset
	return jq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (jq *JibunQuery) Unique(unique bool) *JibunQuery {
	jq.ctx.Unique = &unique
	return jq
}

// Order specifies how the records should be ordered.
func (jq *JibunQuery) Order(o ...OrderFunc) *JibunQuery {
	jq.order = append(jq.order, o...)
	return jq
}

// QueryDemol chains the current query on the "demol" edge.
func (jq *JibunQuery) QueryDemol() *DemolQuery {
	query := (&DemolClient{config: jq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := jq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := jq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(jibun.Table, jibun.FieldID, selector),
			sqlgraph.To(demol.Table, demol.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, jibun.DemolTable, jibun.DemolColumn),
		)
		fromU = sqlgraph.SetNeighbors(jq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Jibun entity from the query.
// Returns a *NotFoundError when no Jibun was found.
func (jq *JibunQuery) First(ctx context.Context) (*Jibun, error) {
	nodes, err := jq.Limit(1).All(setContextOp(ctx, jq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{jibun.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (jq *JibunQuery) FirstX(ctx context.Context) *Jibun {
	node, err := jq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Jibun ID from the query.
// Returns a *NotFoundError when no Jibun ID was found.
func (jq *JibunQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = jq.Limit(1).IDs(setContextOp(ctx, jq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{jibun.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (jq *JibunQuery) FirstIDX(ctx context.Context) int {
	id, err := jq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Jibun entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Jibun entity is found.
// Returns a *NotFoundError when no Jibun entities are found.
func (jq *JibunQuery) Only(ctx context.Context) (*Jibun, error) {
	nodes, err := jq.Limit(2).All(setContextOp(ctx, jq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{jibun.Label}
	default:
		return nil, &NotSingularError{jibun.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (jq *JibunQuery) OnlyX(ctx context.Context) *Jibun {
	node, err := jq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Jibun ID in the query.
// Returns a *NotSingularError when more than one Jibun ID is found.
// Returns a *NotFoundError when no entities are found.
func (jq *JibunQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = jq.Limit(2).IDs(setContextOp(ctx, jq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{jibun.Label}
	default:
		err = &NotSingularError{jibun.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (jq *JibunQuery) OnlyIDX(ctx context.Context) int {
	id, err := jq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Jibuns.
func (jq *JibunQuery) All(ctx context.Context) ([]*Jibun, error) {
	ctx = setContextOp(ctx, jq.ctx, "All")
	if err := jq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Jibun, *JibunQuery]()
	return withInterceptors[[]*Jibun](ctx, jq, qr, jq.inters)
}

// AllX is like All, but panics if an error occurs.
func (jq *JibunQuery) AllX(ctx context.Context) []*Jibun {
	nodes, err := jq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Jibun IDs.
func (jq *JibunQuery) IDs(ctx context.Context) (ids []int, err error) {
	if jq.ctx.Unique == nil && jq.path != nil {
		jq.Unique(true)
	}
	ctx = setContextOp(ctx, jq.ctx, "IDs")
	if err = jq.Select(jibun.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (jq *JibunQuery) IDsX(ctx context.Context) []int {
	ids, err := jq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (jq *JibunQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, jq.ctx, "Count")
	if err := jq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, jq, querierCount[*JibunQuery](), jq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (jq *JibunQuery) CountX(ctx context.Context) int {
	count, err := jq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (jq *JibunQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, jq.ctx, "Exist")
	switch _, err := jq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (jq *JibunQuery) ExistX(ctx context.Context) bool {
	exist, err := jq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the JibunQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (jq *JibunQuery) Clone() *JibunQuery {
	if jq == nil {
		return nil
	}
	return &JibunQuery{
		config:     jq.config,
		ctx:        jq.ctx.Clone(),
		order:      append([]OrderFunc{}, jq.order...),
		inters:     append([]Interceptor{}, jq.inters...),
		predicates: append([]predicate.Jibun{}, jq.predicates...),
		withDemol:  jq.withDemol.Clone(),
		// clone intermediate query.
		sql:  jq.sql.Clone(),
		path: jq.path,
	}
}

// WithDemol tells the query-builder to eager-load the nodes that are connected to
// the "demol" edge. The optional arguments are used to configure the query builder of the edge.
func (jq *JibunQuery) WithDemol(opts ...func(*DemolQuery)) *JibunQuery {
	query := (&DemolClient{config: jq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	jq.withDemol = query
	return jq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		BjdongCd string `json:"bjdong_cd,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Jibun.Query().
//		GroupBy(jibun.FieldBjdongCd).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (jq *JibunQuery) GroupBy(field string, fields ...string) *JibunGroupBy {
	jq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &JibunGroupBy{build: jq}
	grbuild.flds = &jq.ctx.Fields
	grbuild.label = jibun.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		BjdongCd string `json:"bjdong_cd,omitempty"`
//	}
//
//	client.Jibun.Query().
//		Select(jibun.FieldBjdongCd).
//		Scan(ctx, &v)
func (jq *JibunQuery) Select(fields ...string) *JibunSelect {
	jq.ctx.Fields = append(jq.ctx.Fields, fields...)
	sbuild := &JibunSelect{JibunQuery: jq}
	sbuild.label = jibun.Label
	sbuild.flds, sbuild.scan = &jq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a JibunSelect configured with the given aggregations.
func (jq *JibunQuery) Aggregate(fns ...AggregateFunc) *JibunSelect {
	return jq.Select().Aggregate(fns...)
}

func (jq *JibunQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range jq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, jq); err != nil {
				return err
			}
		}
	}
	for _, f := range jq.ctx.Fields {
		if !jibun.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if jq.path != nil {
		prev, err := jq.path(ctx)
		if err != nil {
			return err
		}
		jq.sql = prev
	}
	return nil
}

func (jq *JibunQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Jibun, error) {
	var (
		nodes       = []*Jibun{}
		withFKs     = jq.withFKs
		_spec       = jq.querySpec()
		loadedTypes = [1]bool{
			jq.withDemol != nil,
		}
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, jibun.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Jibun).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Jibun{config: jq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, jq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := jq.withDemol; query != nil {
		if err := jq.loadDemol(ctx, query, nodes,
			func(n *Jibun) { n.Edges.Demol = []*Demol{} },
			func(n *Jibun, e *Demol) { n.Edges.Demol = append(n.Edges.Demol, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (jq *JibunQuery) loadDemol(ctx context.Context, query *DemolQuery, nodes []*Jibun, init func(*Jibun), assign func(*Jibun, *Demol)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Jibun)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Demol(func(s *sql.Selector) {
		s.Where(sql.InValues(jibun.DemolColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.jibun_demol
		if fk == nil {
			return fmt.Errorf(`foreign-key "jibun_demol" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "jibun_demol" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (jq *JibunQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := jq.querySpec()
	_spec.Node.Columns = jq.ctx.Fields
	if len(jq.ctx.Fields) > 0 {
		_spec.Unique = jq.ctx.Unique != nil && *jq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, jq.driver, _spec)
}

func (jq *JibunQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(jibun.Table, jibun.Columns, sqlgraph.NewFieldSpec(jibun.FieldID, field.TypeInt))
	_spec.From = jq.sql
	if unique := jq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if jq.path != nil {
		_spec.Unique = true
	}
	if fields := jq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, jibun.FieldID)
		for i := range fields {
			if fields[i] != jibun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := jq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := jq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := jq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := jq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (jq *JibunQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(jq.driver.Dialect())
	t1 := builder.Table(jibun.Table)
	columns := jq.ctx.Fields
	if len(columns) == 0 {
		columns = jibun.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if jq.sql != nil {
		selector = jq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if jq.ctx.Unique != nil && *jq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range jq.predicates {
		p(selector)
	}
	for _, p := range jq.order {
		p(selector)
	}
	if offset := jq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := jq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// JibunGroupBy is the group-by builder for Jibun entities.
type JibunGroupBy struct {
	selector
	build *JibunQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (jgb *JibunGroupBy) Aggregate(fns ...AggregateFunc) *JibunGroupBy {
	jgb.fns = append(jgb.fns, fns...)
	return jgb
}

// Scan applies the selector query and scans the result into the given value.
func (jgb *JibunGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, jgb.build.ctx, "GroupBy")
	if err := jgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*JibunQuery, *JibunGroupBy](ctx, jgb.build, jgb, jgb.build.inters, v)
}

func (jgb *JibunGroupBy) sqlScan(ctx context.Context, root *JibunQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(jgb.fns))
	for _, fn := range jgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*jgb.flds)+len(jgb.fns))
		for _, f := range *jgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*jgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := jgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// JibunSelect is the builder for selecting fields of Jibun entities.
type JibunSelect struct {
	*JibunQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (js *JibunSelect) Aggregate(fns ...AggregateFunc) *JibunSelect {
	js.fns = append(js.fns, fns...)
	return js
}

// Scan applies the selector query and scans the result into the given value.
func (js *JibunSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, js.ctx, "Select")
	if err := js.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*JibunQuery, *JibunSelect](ctx, js.JibunQuery, js, js.inters, v)
}

func (js *JibunSelect) sqlScan(ctx context.Context, root *JibunQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(js.fns))
	for _, fn := range js.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*js.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := js.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
