// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"gopms/ent/jibun"
	"gopms/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JibunDelete is the builder for deleting a Jibun entity.
type JibunDelete struct {
	config
	hooks    []Hook
	mutation *JibunMutation
}

// Where appends a list predicates to the JibunDelete builder.
func (jd *JibunDelete) Where(ps ...predicate.Jibun) *JibunDelete {
	jd.mutation.Where(ps...)
	return jd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (jd *JibunDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, JibunMutation](ctx, jd.sqlExec, jd.mutation, jd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (jd *JibunDelete) ExecX(ctx context.Context) int {
	n, err := jd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (jd *JibunDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(jibun.Table, sqlgraph.NewFieldSpec(jibun.FieldID, field.TypeInt))
	if ps := jd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, jd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	jd.mutation.done = true
	return affected, err
}

// JibunDeleteOne is the builder for deleting a single Jibun entity.
type JibunDeleteOne struct {
	jd *JibunDelete
}

// Where appends a list predicates to the JibunDelete builder.
func (jdo *JibunDeleteOne) Where(ps ...predicate.Jibun) *JibunDeleteOne {
	jdo.jd.mutation.Where(ps...)
	return jdo
}

// Exec executes the deletion query.
func (jdo *JibunDeleteOne) Exec(ctx context.Context) error {
	n, err := jdo.jd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{jibun.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (jdo *JibunDeleteOne) ExecX(ctx context.Context) {
	if err := jdo.Exec(ctx); err != nil {
		panic(err)
	}
}
