// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"gopms/ent/perms"
	"gopms/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PermsDelete is the builder for deleting a Perms entity.
type PermsDelete struct {
	config
	hooks    []Hook
	mutation *PermsMutation
}

// Where appends a list predicates to the PermsDelete builder.
func (pd *PermsDelete) Where(ps ...predicate.Perms) *PermsDelete {
	pd.mutation.Where(ps...)
	return pd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pd *PermsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, PermsMutation](ctx, pd.sqlExec, pd.mutation, pd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pd *PermsDelete) ExecX(ctx context.Context) int {
	n, err := pd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pd *PermsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(perms.Table, sqlgraph.NewFieldSpec(perms.FieldID, field.TypeInt))
	if ps := pd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pd.mutation.done = true
	return affected, err
}

// PermsDeleteOne is the builder for deleting a single Perms entity.
type PermsDeleteOne struct {
	pd *PermsDelete
}

// Where appends a list predicates to the PermsDelete builder.
func (pdo *PermsDeleteOne) Where(ps ...predicate.Perms) *PermsDeleteOne {
	pdo.pd.mutation.Where(ps...)
	return pdo
}

// Exec executes the deletion query.
func (pdo *PermsDeleteOne) Exec(ctx context.Context) error {
	n, err := pdo.pd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{perms.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pdo *PermsDeleteOne) ExecX(ctx context.Context) {
	if err := pdo.Exec(ctx); err != nil {
		panic(err)
	}
}
