// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gopms/ent/bjd"
	"gopms/ent/demol"
	"gopms/ent/jibun"
	"gopms/ent/perms"
	"gopms/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bjdFields := schema.Bjd{}.Fields()
	_ = bjdFields
	// bjdDescCreatedAt is the schema descriptor for created_at field.
	bjdDescCreatedAt := bjdFields[6].Descriptor()
	// bjd.DefaultCreatedAt holds the default value on creation for the created_at field.
	bjd.DefaultCreatedAt = bjdDescCreatedAt.Default.(func() time.Time)
	// bjdDescUpdatedAt is the schema descriptor for updated_at field.
	bjdDescUpdatedAt := bjdFields[7].Descriptor()
	// bjd.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bjd.DefaultUpdatedAt = bjdDescUpdatedAt.Default.(func() time.Time)
	demolFields := schema.Demol{}.Fields()
	_ = demolFields
	// demolDescMgmPmsrgstPk is the schema descriptor for mgm_pmsrgst_pk field.
	demolDescMgmPmsrgstPk := demolFields[0].Descriptor()
	// demol.MgmPmsrgstPkValidator is a validator for the "mgm_pmsrgst_pk" field. It is called by the builders before save.
	demol.MgmPmsrgstPkValidator = demolDescMgmPmsrgstPk.Validators[0].(func(string) error)
	// demolDescCreatedAt is the schema descriptor for created_at field.
	demolDescCreatedAt := demolFields[16].Descriptor()
	// demol.DefaultCreatedAt holds the default value on creation for the created_at field.
	demol.DefaultCreatedAt = demolDescCreatedAt.Default.(func() time.Time)
	// demolDescUpdatedAt is the schema descriptor for updated_at field.
	demolDescUpdatedAt := demolFields[17].Descriptor()
	// demol.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	demol.DefaultUpdatedAt = demolDescUpdatedAt.Default.(func() time.Time)
	jibunFields := schema.Jibun{}.Fields()
	_ = jibunFields
	// jibunDescCreatedAt is the schema descriptor for created_at field.
	jibunDescCreatedAt := jibunFields[17].Descriptor()
	// jibun.DefaultCreatedAt holds the default value on creation for the created_at field.
	jibun.DefaultCreatedAt = jibunDescCreatedAt.Default.(func() time.Time)
	// jibunDescUpdatedAt is the schema descriptor for updated_at field.
	jibunDescUpdatedAt := jibunFields[18].Descriptor()
	// jibun.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	jibun.DefaultUpdatedAt = jibunDescUpdatedAt.Default.(func() time.Time)
	permsFields := schema.Perms{}.Fields()
	_ = permsFields
	// permsDescCreatedAt is the schema descriptor for created_at field.
	permsDescCreatedAt := permsFields[42].Descriptor()
	// perms.DefaultCreatedAt holds the default value on creation for the created_at field.
	perms.DefaultCreatedAt = permsDescCreatedAt.Default.(func() time.Time)
	// permsDescUpdatedAt is the schema descriptor for updated_at field.
	permsDescUpdatedAt := permsFields[43].Descriptor()
	// perms.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	perms.DefaultUpdatedAt = permsDescUpdatedAt.Default.(func() time.Time)
}
