// Code generated by ent, DO NOT EDIT.

package demol

import (
	"time"
)

const (
	// Label holds the string label denoting the demol type in the database.
	Label = "demol"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMgmPmsrgstPk holds the string denoting the mgm_pmsrgst_pk field in the database.
	FieldMgmPmsrgstPk = "mgm_pmsrgst_pk"
	// FieldBldNm holds the string denoting the bld_nm field in the database.
	FieldBldNm = "bld_nm"
	// FieldDemolExtngGBCd holds the string denoting the demol_extng_gb_cd field in the database.
	FieldDemolExtngGBCd = "demol_extng_gb_cd"
	// FieldDemolExtngGBCdNm holds the string denoting the demol_extng_gb_cd_nm field in the database.
	FieldDemolExtngGBCdNm = "demol_extng_gb_cd_nm"
	// FieldDemolStrtDay holds the string denoting the demol_strt_day field in the database.
	FieldDemolStrtDay = "demol_strt_day"
	// FieldDemolEndDay holds the string denoting the demol_end_day field in the database.
	FieldDemolEndDay = "demol_end_day"
	// FieldDemolExtngDay holds the string denoting the demol_extng_day field in the database.
	FieldDemolExtngDay = "demol_extng_day"
	// FieldTotArea holds the string denoting the tot_area field in the database.
	FieldTotArea = "tot_area"
	// FieldBldCnt holds the string denoting the bld_cnt field in the database.
	FieldBldCnt = "bld_cnt"
	// FieldMainPurpsCd holds the string denoting the main_purps_cd field in the database.
	FieldMainPurpsCd = "main_purps_cd"
	// FieldMainPurpsCdNm holds the string denoting the main_purps_cd_nm field in the database.
	FieldMainPurpsCdNm = "main_purps_cd_nm"
	// FieldStrctCd holds the string denoting the strct_cd field in the database.
	FieldStrctCd = "strct_cd"
	// FieldStrctCdNm holds the string denoting the strct_cd_nm field in the database.
	FieldStrctCdNm = "strct_cd_nm"
	// FieldHhldCnt holds the string denoting the hhld_cnt field in the database.
	FieldHhldCnt = "hhld_cnt"
	// FieldHoCnt holds the string denoting the ho_cnt field in the database.
	FieldHoCnt = "ho_cnt"
	// FieldCrtnDay holds the string denoting the crtn_day field in the database.
	FieldCrtnDay = "crtn_day"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the demol in the database.
	Table = "demols"
)

// Columns holds all SQL columns for demol fields.
var Columns = []string{
	FieldID,
	FieldMgmPmsrgstPk,
	FieldBldNm,
	FieldDemolExtngGBCd,
	FieldDemolExtngGBCdNm,
	FieldDemolStrtDay,
	FieldDemolEndDay,
	FieldDemolExtngDay,
	FieldTotArea,
	FieldBldCnt,
	FieldMainPurpsCd,
	FieldMainPurpsCdNm,
	FieldStrctCd,
	FieldStrctCdNm,
	FieldHhldCnt,
	FieldHoCnt,
	FieldCrtnDay,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "demols"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"jibun_demol",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// MgmPmsrgstPkValidator is a validator for the "mgm_pmsrgst_pk" field. It is called by the builders before save.
	MgmPmsrgstPkValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)
