// Code generated by ent, DO NOT EDIT.

package bjd

import (
	"time"
)

const (
	// Label holds the string label denoting the bjd type in the database.
	Label = "bjd"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBjdongCd holds the string denoting the bjdong_cd field in the database.
	FieldBjdongCd = "bjdong_cd"
	// FieldSigunguCd holds the string denoting the sigungu_cd field in the database.
	FieldSigunguCd = "sigungu_cd"
	// FieldSidoNm holds the string denoting the sido_nm field in the database.
	FieldSidoNm = "sido_nm"
	// FieldSigunguNm holds the string denoting the sigungu_nm field in the database.
	FieldSigunguNm = "sigungu_nm"
	// FieldDongNm holds the string denoting the dong_nm field in the database.
	FieldDongNm = "dong_nm"
	// FieldLiNm holds the string denoting the li_nm field in the database.
	FieldLiNm = "li_nm"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeJibun holds the string denoting the jibun edge name in mutations.
	EdgeJibun = "jibun"
	// Table holds the table name of the bjd in the database.
	Table = "bjds"
	// JibunTable is the table that holds the jibun relation/edge.
	JibunTable = "jibuns"
	// JibunInverseTable is the table name for the Jibun entity.
	// It exists in this package in order to avoid circular dependency with the "jibun" package.
	JibunInverseTable = "jibuns"
	// JibunColumn is the table column denoting the jibun relation/edge.
	JibunColumn = "bjd_jibun"
)

// Columns holds all SQL columns for bjd fields.
var Columns = []string{
	FieldID,
	FieldBjdongCd,
	FieldSigunguCd,
	FieldSidoNm,
	FieldSigunguNm,
	FieldDongNm,
	FieldLiNm,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)
