// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bjd is the predicate function for bjd builders.
type Bjd func(*sql.Selector)

// Demol is the predicate function for demol builders.
type Demol func(*sql.Selector)

// Jibun is the predicate function for jibun builders.
type Jibun func(*sql.Selector)

// Perms is the predicate function for perms builders.
type Perms func(*sql.Selector)
